version: "2.2"

services:
  app:
    container_name: app
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "
      gunicorn app.wsgi:application --bind 0.0.0.0:8500
      "
    volumes:
      - ./:/app/
      - static_volume:/usr/local/lib/python3.8/site-packages/django/contrib/admin/static
    ports:
      - "8500:8500"
    env_file:
      - .env.deploy
    depends_on:
      - postgres

  postgres:
    container_name: app_postgres
    restart: always
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgres/data/
    ports:
      - "5500:5500"
    env_file:
      - .env.deploy

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - app
    ports:
      - "50:50"
    volumes:
      - static_volume:/var/www/html/static
      - ./nginx-conf.d:/etc/nginx/conf.d/default.conf

volumes:
  pg_data:
  static_volume:
