# Generated by Django 3.2.12 on 2022-07-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='tag',
        ),
        migrations.AddField(
            model_name='images',
            name='tags',
            field=models.TextField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
