# Generated by Django 3.2.12 on 2022-07-12 00:27

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20220711_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_mini',
            field=models.ImageField(upload_to=images.models.user_directory_path),
        ),
    ]
