# Generated by Django 3.2.12 on 2022-07-12 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_images_image_mini'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_mini',
        ),
    ]
